name: Deploy
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: react-app/package-lock.json

    - name: Build React App
      working-directory: react-app
      run: npm install && CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build

    - name: Copy React build to Flask static
      run: mkdir -p app/static && cp react-app/build/index.html react-app/build/favicon.ico app/static/ && cp -r react-app/build/static/. app/static/

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: vercel --prod --token=$VERCEL_TOKEN
